<?
	if (!defined('INNER')) exit;

	$link_form = array(
		'title' => array('caption' => 'Title',
				'data_type' => 'text',
				'html_type' => 'text',
				'length'    => 255,
				'empty'     => false,
				'field'     => 'title'),

		'url' => array('caption' => 'URL',
				'data_type' => 'text',
				'html_type' => 'text',
				'length'    => 255,
				'empty'     => false,
				'field'     => 'url'),

		'link_picture' => array('caption' => 'Picture',
						'data_type' => 'file',
						'html_type' => 'file',
						'ask_width' => 135,
						'ask_height'=> 110,
						'empty'     => true),

		'ordi'  => array('caption' => 'Sort',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'    => 11,
						'empty'     => true,
						'field'     => 'ordi'),

		'intro' => array('caption' => 'Intro',
				'data_type' => 'text',
				'html_type' => 'textarea',
				'empty'     => true,
				'rows'      => 5,
				'field'     => 'intro'));


	$shedule_form = array(
		'shedule_name' => array('caption' => 'Name',
				'data_type' => 'text',
				'html_type' => 'text',
				'length'    => 255,
				'empty'     => false,
				'field'     => 'name'),

		'shedule_email' => array('caption' => 'Email',
				'data_type' => 'email',
				'html_type' => 'text',
				'length'    => 255,
				'empty'     => false,
				'field'     => 'email'),

		'shedule_phone' => array('caption' => 'Phone Number',
				'data_type' => 'text',
				'html_type' => 'text',
				'length'    => 255,
				'empty'     => false,
				'field'     => 'phone'),

		'shedule_date' => array('caption' => 'Preferred Date',
				'data_type' => 'date',
				'html_type' => 'date',
				'is_time'   => true,
				'cur_year'  => true,
				'length'    => 255,
				'empty'     => true,
				'field'     => 'date_pref'),

		'shedule_date_alt' => array('caption' => 'Alternate Date',
				'data_type' => 'date',
				'html_type' => 'date',
				'is_time'   => true,
				'cur_year'  => true,
				'length'    => 255,
				'empty'     => true,
				'field'     => 'date_alt'),

		'shedule_notes' => array('caption' => 'Comments',
				'data_type' => 'text',
				'html_type' => 'textarea',
				'rows'      => 5,
				'empty'     => true,
				'field'     => 'notes')
	);

	$order_form = array(
		'fname' => array('caption'  => 'First name',
						'html_type' => 'text',
						'data_type' => 'text',
						'length'    => 255,
						'empty'     => false,
						'field'     => 'fname'),

		'lname' => array('caption' => 'Last name',
						'html_type' => 'text',
						'data_type' => 'text',
						'length'   => 255,
						'empty'    => false,
						'field'    => 'lname'),

		'email' => array('caption' => 'E-mail',
						'data_type' => 'email',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => false,
						'field'    => 'email'),

		'type' => array('caption' => 'Type of property',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'type'),

		'price_min' => array('caption' => 'Minimum price range',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'price_min'),

		'price_max' => array('caption' => 'Maximum price range',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'price_max'),

		'bedr' => array('caption' => 'Minimum number of bedrooms',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'bedr'),

		'bathr' => array('caption' => 'Minimum number of bathrooms',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'bathr'),

		'square' => array('caption' => 'Minimum square footage',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'square'),

		'soon' => array('caption' => 'How soon are looking to buy',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'soon'),

		'city_desired' => array('caption' => 'Cities desired',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'city_desired'),

		'phone' => array('caption' => 'Phone',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => false,
						'field'    => 'phone'),

		'address' => array('caption' => 'Address',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'address'),

		'city' => array('caption' => 'City',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'city'),

		'state' => array('caption' => 'State',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'state'),

		'zip' => array('caption' => 'ZIP',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'zip'),

		'notes' => array('caption' => 'Questions or Comments',
						'data_type' => 'text',
						'html_type' => 'textarea',
						'empty'    => true,
						'field'    => 'notes'));

	$sell_form = array(
		'fname' => array('caption'  => 'First name',
						'html_type' => 'text',
						'data_type' => 'text',
						'length'    => 255,
						'empty'     => false,
						'field'     => 'fname'),

		'lname' => array('caption' => 'Last name',
						'html_type' => 'text',
						'data_type' => 'text',
						'length'   => 255,
						'empty'    => false,
						'field'    => 'lname'),

		'email' => array('caption' => 'E-mail',
						'data_type' => 'email',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => false,
						'field'    => 'email'),

		'type' => array('caption' => 'Type of property',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'type'),
		
		'price' => array('caption'  => 'Price',
						'html_type' => 'text',
						'data_type' => 'text',
						'length'    => 255,
						'empty'     => true,
						'field'     => 'price'),

		'bedr' => array('caption' => 'Number of bedrooms',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'bedr'),

		'bathr' => array('caption' => 'Number of bathrooms',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'bathr'),

		'square' => array('caption' => 'Square footage',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'square'),

		'home_address' => array('caption' => 'Address',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'home_address'),

		'home_city' => array('caption' => 'City',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'home_city'),

		'home_state' => array('caption' => 'State',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'home_state'),

		'home_zip' => array('caption' => 'ZIP',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'home_zip'),

		'client_phone' => array('caption' => 'Client phone',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => false,
						'field'    => 'client_phone'),

		/*'client_address' => array('caption' => 'Client address',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'client_address'),

		'client_city' => array('caption' => 'Client city',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'client_city'),

		'client_state' => array('caption' => 'Client state',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'client_state'),

		'client_zip' => array('caption' => 'ZIP',
						'data_type' => 'text',
						'html_type' => 'text',
						'length'   => 255,
						'empty'    => true,
						'field'    => 'client_zip'),*/

		'notes' => array('caption' => 'Questions or Comments',
						'data_type' => 'text',
						'html_type' => 'textarea',
						'empty'    => true,
						'field'    => 'notes'));
	
	$check_form = array(
				'html'  => 'KRF_CheckText',
				'text'  => 'KRF_CheckText',
				'email' => 'KRF_validatemailboxname',
				'date'  => 'KRF_CheckDate',
				'file'  => 'KRF_CheckFile'
			);

	$prop_types = array(
		'Single Family'	=> 'Single Family',
		'Town Home'     => 'Town Home',
		'Condominium'   => 'Condominium',
		'Land'          => 'Land',
		'Commercial'    => 'Commercial',
		'Investment'    => 'Investment'	);

	$price_ranges = array(
		0 => '$0',
		10000 => '$10,000',
		20000 => '$20,000',
		30000 => '$30,000',
		40000 => '$40,000',
		50000 => '$50,000',
		60000 => '$6,000',
		70000 => '$7,000',
		75000 => '$7,500',
		100000 => '$100,000',
		125000 => '$125,000',
		150000 => '$150,000',
		175000 => '$175,000',
		200000 => '$200,000',
		225000 => '$225,000',
		250000 => '$250,000',
		275000 => '$275,000',
		300000 => '$300,000',
		325000 => '$325,000',
		350000 => '$350,000',
		400000 => '$400,000',
		450000 => '$450,000',
		500000 => '$500,000',
		550000 => '$550,000',
		600000 => '$600,000',
		650000 => '$650,000',
		700000 => '$700,000',
		750000 => '$750,000',
		800000 => '$800,000',
		950000 => '$950,000',
		1000000 => '$1,000,000',
		1500000 => '$1,500,000',
		2000000 => '$2,000,000',
		2500000 => '$2,500,000',
		3000000 => '$3,000,000',
		3500000 => '$3,500,000',
		4000000 => '$4,000,000',
		4500000 => '$4,500,000',
		5000000 => '$5,000,000',
		6000000 => '$6,000,000',
		8000000 => '$8,000,000',
		10000000 => '$10,000,000');

	$squares = array(
		'any' => 'any',
		600   => 600,
		800   => 800,
		1000   => 1000,
		1200   => 1200,
		1800   => 1800,
		2000   => 2000,
		2250   => 2250,
		2500   => 2500,
		2750   => 2750,
		3000   => 3000,
		3500   => 3500,
		'4000+' => '4000+');

	$soons = array(
			'Immediately' => 'Immediately',
			'Three Months' => 'Three Months',
			'Six Months'   => 'Six Months',
			'One Year'     => 'One Year',
			'Not Sure'     => 'Not Sure'
		);

	$states = array(
'Alaska' =>            'Alaska',        
'Arizona' =>           'Arizona',       
'Arkansas' =>          'Arkansas',      
'California' =>        'California',    
'Colorado' =>          'Colorado',      
'Connecticut' =>       'Connecticut',   
'Deleware' =>          'Deleware',      
'Florida' =>           'Florida',       
'Georgia' =>           'Georgia',       
'Hawaii' =>            'Hawaii',        
'Idaho' =>             'Idaho',         
'Illinois' =>          'Illinois',      
'Indiana' =>           'Indiana',       
'Iowa' =>              'Iowa',          
'Kansas' =>            'Kansas',        
'Kentucky' =>          'Kentucky',      
'Louisiana' =>         'Louisiana',     
'Maine' =>             'Maine',         
'Maryland' =>          'Maryland',      
'Massachusetts' =>     'Massachusetts', 
'Michigan' =>          'Michigan',      
'Minnesota' =>         'Minnesota',     
'Mississippi' =>       'Mississippi',
'Iowa' =>              'Iowa',          
'Montana' =>           'Montana',       
'Nebraska' =>          'Nebraska',      
'Nevada' =>            'Nevada',        
'New Hampshire' =>     'New Hampshire', 
'New Jersey' =>        'New Jersey',    
'New Mexico' =>        'New Mexico',    
'New York' =>          'New York',      
'North Carolina' =>    'North Carolina',
'North Dakota' =>      'North Dakota',
'Ohio' =>              'Ohio',          
'Oklahoma' =>          'Oklahoma',      
'Oregon' =>            'Oregon',        
'Pennsylvania' =>      'Pennsylvania',  
'Rhode Island' =>      'Rhode Island',  
'South Carolina' =>    'South Carolina',
'South Dakota' =>      'South Dakota',  
'Tennessee' =>         'Tennessee',     
'Texas' =>             'Texas',         
'Utah' =>              'Utah',          
'Vermont' =>           'Vermont',       
'Viriginia' =>         'Viriginia',
'Washington' =>        'Washington',    
'Washington DC' =>     'Washington DC', 
'West Virignia' =>     'West Virignia',
'Wisconsin' =>         'Wisconsin',     
'Wyoming' =>           'Wyoming');
?>
