if(document.all){
document.writeln('<Div id="popitup" class="menuBack" style="width:132">')
document.writeln('<Div id="popmenu" class="menuBorder" style="width:132">')
document.writeln('<Div id="mainmenuitem1" class="orange" style="width:132">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;PCs&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem2" class="menuItem" style="width:132" onmouseout="udspl(this.id)" onmouseover="cdspl(this.id,false)" onclick="gomenu(\'pcs.html#top\');mdspl()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Desktops&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem3" class="menuItem" style="width:132" onmouseout="udspl(this.id)" onmouseover="cdspl(this.id,false)" onclick="gomenu(\'pcs.html#menu2\');mdspl()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Workstations&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem4" class="menuItem" style="width:132">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem5" class="orange" style="width:132">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Servers&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem6" class="menuItem" style="width:132" onmouseout="udspl(this.id)" onmouseover="cdspl(this.id,false)" onclick="gomenu(\'servers.html#top\');mdspl()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Entry&nbsp;Level&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem7" class="menuItem" style="width:132" onmouseout="udspl(this.id)" onmouseover="cdspl(this.id,false)" onclick="gomenu(\'servers.html#menu2\');mdspl()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Mid&nbsp;Level&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem8" class="menuItem" style="width:132" onmouseout="udspl(this.id)" onmouseover="cdspl(this.id,false)" onclick="gomenu(\'servers.html#menu3\');mdspl()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;High&nbsp;Level&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem9" class="menuItem" style="width:132" onmouseout="udspl(this.id)" onmouseover="cdspl(this.id,false)" onclick="gomenu(\'servers.html#menu4\');mdspl()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Enterprise&nbsp;Level&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem10" class="menuItem" style="width:132">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem11" class="orange" style="width:132">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Peripherals&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem12" class="menuItem" style="width:132" onmouseout="udspl(this.id)" onmouseover="cdspl(this.id,false)" onclick="gomenu(\'peripherals.html\');mdspl()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Manufacturers&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem13" class="menuItem" style="width:132">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem14" class="orange" style="width:132">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Software&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem15" class="menuItem" style="width:132" onmouseout="udspl(this.id)" onmouseover="cdspl(this.id,false)" onclick="gomenu(\'misc_software.html#top\');mdspl()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Citrix&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem16" class="menuItem" style="width:132" onmouseout="udspl(this.id)" onmouseover="cdspl(this.id,false)" onclick="gomenu(\'misc_software.html#menu2\');mdspl()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sage&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem17" class="menuItem" style="width:132" onmouseout="udspl(this.id)" onmouseover="cdspl(this.id,true)">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Microsoft<Img id="arowmainmenuitem17" Src="pop_arw.gif" style="position:absolute;top:7px">&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem18" class="menuItem" style="width:132" onmouseout="udspl(this.id)" onmouseover="cdspl(this.id,false)" onclick="gomenu(\'misc_software.html#menu3\');mdspl()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Symantec&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem19" class="menuItem" style="width:132" onmouseout="udspl(this.id)" onmouseover="cdspl(this.id,true)">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tivoli<Img id="arowmainmenuitem19" Src="pop_arw.gif" style="position:absolute;top:7px">&nbsp;&nbsp;</Div>')
document.writeln('<Div id="mainmenuitem20" class="menuItem" style="width:132" onmouseout="udspl(this.id)" onmouseover="cdspl(this.id,false)" onclick="gomenu(\'elron_software.html\');mdspl()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Elron&nbsp;&nbsp;</Div>')
document.writeln('</Div>')
document.writeln('</Div>')
document.writeln('<Div id="17subout" class="menuBack" style="width:101" style="width:132">')
document.writeln('<Div id="17subin" class="menuBorder" style="width:101" style="width:132">')
document.writeln('<Div id="17subitem1" class="menuItem" style="width:132" onmouseover="cdspl(this.id)" onmouseout="udspl(this.id)" onclick="gomenu(\'microsoft_software.html#top\');mdspl()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Backoffice&nbsp;&nbsp;</Div>')
document.writeln('<Div id="17subitem2" class="menuItem" style="width:132" onmouseover="cdspl(this.id)" onmouseout="udspl(this.id)" onclick="gomenu(\'microsoft_software.html#menu2\');mdspl()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Office&nbsp;&nbsp;</Div>')
document.writeln('<Div id="17subitem3" class="menuItem" style="width:132" onmouseover="cdspl(this.id)" onmouseout="udspl(this.id)" onclick="gomenu(\'microsoft_software.html#menu3\');mdspl()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Windows&nbsp;&nbsp;</Div>')
document.writeln('</Div>')
document.writeln('</Div>')
document.writeln('<Div id="19subout" class="menuBack" style="width:128">')
document.writeln('<Div id="19subin" class="menuBorder" style="width:128">')
document.writeln('<Div id="19subitem1" class="menuItem" style="width:132" onmouseover="cdspl(this.id)" onmouseout="udspl(this.id)" onclick="gomenu(\'tivoli_software.html#top\');mdspl()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;IT&nbsp;Director&nbsp;&nbsp;</Div>')
document.writeln('<Div id="19subitem2" class="menuItem" style="width:132" onmouseover="cdspl(this.id)" onmouseout="udspl(this.id)" onclick="gomenu(\'tivoli_software.html#menu2\');mdspl()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Data&nbsp;Protection&nbsp;&nbsp;</Div>')
document.writeln('</Div>')
document.writeln('</Div>')
document.close();
}
